language: node_js
node_js:
  - "4.4.5"
sudo: true
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
before_script:
  - 'cd web'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'npm install'
script:
  - 'grunt build karma'
