language: node_js
node_js:
  - "6"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
before_script:
  - mongo tournament-auto-tests scripts/testdb-seed.js
  - npm install -g bower grunt-cli
  - npm install
script:
  - npm test
  - cd web && grunt karma
