dist: xenial
language: node_js
node_js:
  - "8"
services:
  - mongodb
before_script:
  - mongo tournament-auto-tests scripts/testdb-seed.js
  - npm install
script:
  - npm test
  - cd web && grunt karma
