dist: xenial
language: node_js
node_js:
  - "10"
  - "12"
services:
  - mongodb
before_script:
  - mongo tournament-auto-tests scripts/testdb-seed.js
  - npm install
script:
  - npm run test:server
  - npm run test:unit
