language: node_js
node_js:
  - "4"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - mongodb-org-server
      - mongodb
before_script:
  - 'npm install'
  - 'cd web'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'npm install'
  - 'cd ..'
script:
  - 'npm test'
  - 'cd web && grunt build karma'
